In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.linear_model import LinearRegression
lr2 = LinearRegression()

In [2]:
data=pd.read_csv('student_habits_performance.csv')

In [3]:
data.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [4]:
data.drop(['parental_education_level','diet_quality','internet_quality'],axis=1,inplace=True)

In [5]:
data.gender = data.gender.apply(lambda x: 1 if x=='Female' else 0)
data.part_time_job = data.part_time_job.apply(lambda x: 1 if x=='Yes' else 0)
data.extracurricular_participation = data.extracurricular_participation.apply(lambda x: 1 if x=='Yes' else 0)

In [6]:
data['student_id']=data['student_id'].str.replace('S','').astype(int)

In [8]:
data.corr()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,extracurricular_participation,exam_score
student_id,1.000000,-0.028505,0.015617,-0.026012,-0.037516,-0.030793,0.049703,-0.072613,-0.065830,-0.007175,0.037973,0.027478,-0.021489
age,-0.028505,1.000000,-0.031699,0.003971,-0.009151,-0.001174,-0.011680,-0.026055,0.037482,-0.003836,-0.045101,-0.004993,-0.008907
gender,0.015617,-0.031699,1.000000,0.022087,-0.001273,-0.019511,-0.036124,0.024575,0.001277,-0.064462,0.005149,0.004478,0.007977
study_hours_per_day,-0.026012,0.003971,0.022087,1.000000,0.020282,-0.031158,-0.029133,0.026264,-0.027757,-0.028701,-0.003768,-0.003264,0.825419
social_media_hours,-0.037516,-0.009151,-0.001273,0.020282,1.000000,0.011477,0.021224,0.040479,0.018236,-0.037319,0.001496,-0.018597,-0.166733
netflix_hours,-0.030793,-0.001174,-0.019511,-0.031158,0.011477,1.000000,0.009207,-0.002092,-0.000935,-0.006448,0.008034,-0.005125,-0.171779
part_time_job,0.049703,-0.011680,-0.036124,-0.029133,0.021224,0.009207,1.000000,-0.041771,0.001645,-0.021679,0.013539,-0.022841,-0.026608
attendance_percentage,-0.072613,-0.026055,0.024575,0.026264,0.040479,-0.002092,-0.041771,1.000000,0.013756,-0.007857,-0.018745,-0.017778,0.089836
sleep_hours,-0.065830,0.037482,0.001277,-0.027757,0.018236,-0.000935,0.001645,0.013756,1.000000,0.019769,-0.006508,0.027693,0.121683
exercise_frequency,-0.007175,-0.003836,-0.064462,-0.028701,-0.037319,-0.006448,-0.021679,-0.007857,0.019769,1.000000,-0.000242,-0.005681,0.160107
mental_health_rating,0.037973,-0.045101,0.005149,-0.003768,0.001496,0.008034,0.013539,-0.018745,-0.006508,-0.000242,1.000000,-0.004741,0.321523
extracurricular_participation,0.027478,-0.004993,0.004478,-0.003264,-0.018597,-0.005125,-0.022841,-0.017778,0.027693,-0.005681,-0.004741,1.000000,0.000881
exam_score,-0.021489,-0.008907,0.007977,0.825419,-0.166733,-0.171779,-0.026608,0.089836,0.121683,0.160107,0.321523,0.000881,1.000000

In [9]:
X=data.drop('exam_score',axis=1)
y=data['exam_score']

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
lr2.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred_train = lr2.predict(X_train)

In [13]:
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
mean_squared_error(y_train, y_pred_train)

28.384294654183115

In [15]:
r2_score(y_train,y_pred_train)

0.9013600068754051

In [16]:
lr2.score(X_test,y_test)

0.8976454546484989